name: "Configure Nextflow for MAJIQ"
description: "Set MAJIQ container overrides and inject the MAJIQ license secret"
inputs:
  image_name:
    description: "Docker image name to use for all MAJIQ processes (e.g. majiq:latest)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Create Nextflow user config directory
      shell: bash
      run: |
        mkdir -p ~/.nextflow

    - name: Write MAJIQ container overrides into ~/.nextflow/config
      shell: bash
      run: |
        cat > ~/.nextflow/config <<EOF
        process {
              // majiq (required)
              withName: 'MAJIQ_BUILDGFF3'         { container = 'majiq:latest'                   }
              withName: 'MAJIQ_BUILDSJ'           { container = 'majiq:latest'                   }
              withName: 'MAJIQ_BUILDUPDATE'       { container = 'majiq:latest'                   }
              withName: 'MAJIQ_PSICOVERAGE'       { container = 'majiq:latest'                   }
              withName: 'MAJIQ_PSI'               { container = 'majiq:latest'                   }
              withName: 'MAJIQ_DELTAPSI'          { container = 'majiq:latest'                   }
              withName: 'MAJIQ_HETEROGEN'         { container = 'majiq:latest'                   }
              withName: 'MAJIQ_SGCOVERAGE'        { container = 'majiq:latest'                   }
              withName: 'DELTAPSI_MODULIZE'       { container = 'majiq:latest'                   }
              withName: 'HETEROGEN_MODULIZE'      { container = 'majiq:latest'                   }
          }
        }
        EOF

        echo "Nextflow user config (~/.nextflow/config) written successfully:"
        cat ~/.nextflow/config

    - name: Inject MAJIQ license into Nextflow secrets
      shell: bash
      env:
        MAJIQ_LICENSE: ${{ secrets.MAJIQ_LICENSE }}
      run: |
        echo "Injecting MAJIQ_LICENSE secret into nextflow secrets..."
        nextflow secrets set MAJIQ_LICENSE "$MAJIQ_LICENSE"
        echo "MAJIQ_LICENSE secret configured."
